CREATE TYPE [dbo].[UserInformation_ID] AS TABLE (
    [ID]                 INT            NOT NULL,
    [Name]               NVARCHAR (50)  NULL,
    [Family]             NVARCHAR (50)  NULL,
    [UserName]           NVARCHAR (50)  NULL,
    [Password]           NVARCHAR (200) NULL,
    [PasswordNew]        NVARCHAR (200) NULL,
    [PasswordSult]       NVARCHAR (200) NULL,
    [Picture]            NVARCHAR (50)  NULL,
    [Email]              NVARCHAR (50)  NULL,
    [Phone]              NVARCHAR (50)  NULL,
    [F_M]                NVARCHAR (50)  NULL,
    [Website]            NVARCHAR (50)  NULL,
    [ftMVC_EducationsID] INT            NULL,
    [InstagramID]        NVARCHAR (50)  NULL,
    [State]              NVARCHAR (50)  NULL,
    [City]               NVARCHAR (50)  NULL,
    [Biography]          NVARCHAR (50)  NULL,
    [googleAccount]      NVARCHAR (50)  NULL,
    [Active]             BIT            NULL,
    [UUID]               NCHAR (50)     NULL,
    [Question]           NVARCHAR (50)  NULL,
    [Answer]             NVARCHAR (50)  NULL,
    [Phone_OK]           BIT            NULL,
    [Email_OK]           BIT            NULL,
    [Code]               NVARCHAR (50)  NULL,
    [HasChannel]         BIT            NULL,
    [CommentCount]       INT            NULL,
    [LikeCount]          INT            NULL,
    [DislikeCount]       INT            NULL,
    [PostCount]          INT            NULL,
    [SaveCount]          INT            NULL,
    [ShareCount]         INT            NULL,
    [BookmarkCount]      INT            NULL,
    [MessageCount]       INT            NULL,
    [Result]             NVARCHAR (50)  NULL,
    [Message]            NVARCHAR (50)  NULL);


GO

